### ISSUE TITLE
migrate logger

### ISSUE THREAD

**Issue by mikeAdamss** [ONSdigital/dp-python-tools#25]
## What is this

Migrate the logger from:
https://github.com/GSS-Cogs/dp-python-tools/tree/main

to:
https://github.com/ONSdigital/dp-python-tools

## What to do

Create as a new PR. As part of this I'd also like a few changes:

- 1. Investigate removing the "test_mode" keyword please, that was a bit of a quick hack as we were in a rush. Look for a non invasive way to capture what's being sent to the logger while testing.

- 2. Add documentation for how to use the logger. Use the other readmes in https://github.com/ONSdigital/dp-python-tools as a guide for style and level od detail.

## Acceptance Criteria

- [ ] Logger migrated and tests work with new "no test_mode" approach.

**Comment by martynspooner** [comment]
5pts.

**Comment by mikeAdamss** [comment]
gone a different way
